# Generated Meson configuration for sub-module: Debug

oolite_sources += files(
    'OODebugMonitor.mm',
    'OODebugMonitor+ObjCBridge.mm',
    'OODebugStandards.mm',
    'OODebugSupport.mm',
    'OODebugSupport+ObjCBridge.mm',
    'OODebugTCPConsoleClient.mm',
    'OODebugTCPConsoleClient+ObjCBridge.mm',
    'OOJSConsole.mm',
    'OOJSConsole+ObjCBridge.mm',
    'OOTCPStreamDecoder.c',
    'OOTCPStreamDecoderAbstractionLayer.mm',
)

oolite_includes += include_directories('.')

