# Generated Meson configuration for sub-module: Debug

oolite_sources += files(
    'OODebugMonitor.mm',
    'OODebugStandards.mm',
    'OODebugStandards+FoundationBridge.mm',
    'OODebugSupport.mm',
    'OODebugTCPConsoleClient.mm',
    'OOJSConsole.mm',
    'OOTCPStreamDecoder.c',
    'OOTCPStreamDecoderAbstractionLayer.mm',
)

oolite_includes += include_directories('.')

