# Generated Meson configuration for sub-module: Core

oolite_sources += files(
    'AI.mm',
    'AI+ObjCBridge.mm',
    'AIGraphViz.mm',
    'CollisionRegion.mm',
    'CollisionRegion+ObjCBridge.mm',
    'GameController.mm',
    'GuiDisplayGen.mm',
    'HeadUpDisplay.mm',
    'HeadUpDisplay+ObjCBridge.mm',
    'NSObjectOOExtensions.mm',
    'OOALBufferedSound.mm',
    'OOALBufferedSound+ObjCBridge.mm',
    'OOALMusic.mm',
    'OOALMusic+ObjCBridge.mm',
    'OOALSound.mm',
    'OOALSound+ObjCBridge.mm',
    'OOALSoundChannel.mm',
    'OOALSoundChannel+ObjCBridge.mm',
    'OOALSoundDecoder.mm',
    'OOALSoundDecoder+ObjCBridge.mm',
    'OOALSoundMixer.mm',
    'OOALSoundMixer+ObjCBridge.mm',
    'OOALStreamedSound.mm',
    'OOALStreamedSound+ObjCBridge.mm',
    'OOAsyncQueue.mm',
    'OOAsyncWorkManager.mm',
    'OOAsyncWorkManager+ObjCBridge.mm',
    'OOBasicSoundReferencePoint.mm',
    'OOCPUInfo.mm',
    'OOCache.mm',
    'OOCacheManager.mm',
    'OOCacheManager+ObjCBridge.mm',
    'OOCallByName.mm',
      'OOCharacter.mm',
      'OOCharacter+ObjCBridge.mm',
    'OOCocoa.mm',
    'OOColor.mm',
    'OOColor+ObjCBridge.mm',
    'OOCommodities.mm',
    'OOCommodities+ObjCBridge.mm',
    'OOCommodityMarket.mm',
    'OOCommodityMarket+ObjCBridge.mm',
    'OOConstToString.mm',
    'OOConvertCubeMapToLatLong.mm',
    'OOConvertSystemDescriptions.mm',
    'OOCrosshairs.mm',
    'OODataFromOXZFile.mm',
    'OODebugGLDrawing.mm',
    'OODescription.mm',
    'OODrawable.mm',
    'OODrawable+ObjCBridge.mm',
    'OOEncodingConverter.mm',
    'OOEntityFilterPredicate.mm',
    'OOEquipmentType.mm',
    'OOEquipmentType+ObjCBridge.mm',
    'OOFullScreenController.mm',
    'OOGraphicsResetManager.mm',
    'OOGraphicsResetManager+ObjCBridge.mm',
    'OOHPVector.mm',
    'OOIsNumberLiteral.cpp',
    'OOJoystickManager.mm',
    'OOJoystickManager+ObjCBridge.mm',
    'OOJoystickProfile.mm',
    'OOJoystickProfile+ObjCBridge.mm',
    'OOLogHeader.mm',
    'OOLogOutputHandler.mm',
    'OOLogging.mm',
    'OOMatrix.mm',
    'OOMesh.mm',
    'OOMeshToOctreeConverter.mm',
    'OOMeshToOctreeConverter+ObjCBridge.mm',
    'OOMouseInteractionMode.cpp',
    'OOMusicController.mm',
    'OOMusicController+ObjCBridge.mm',
    'OOOXZManager.mm',
    'OOOpenALController.mm',
    'OOOpenGL.mm',
    'OOOpenGLExtensionManager.mm',
    'OOOpenGLExtensionManager+ObjCBridge.mm',
    'OOOpenGLMatrixManager.mm',
    'OOOpenGLMatrixManager+ObjCBridge.mm',
    'OOOpenGLStateManager.mm',
    'OOPListParsing.mm',
    'OOPListGameTypes.mm',
    'OOPlanetData.c',
    'OOPlanetDrawable.mm',
    'OOPolygonSprite.mm',
    'OOPolygonSprite+ObjCBridge.mm',
    'OOPriorityQueue.mm',
    'OOProbabilisticTextureManager.mm',
    'OOProbabilitySet.mm',
    'OOProfilingStopwatch.mm',
    'OOQuaternion.cpp',
    'OORegExpMatcher.mm',
    'OORegExpMatcher+ObjCBridge.mm',
    'OORoleSet.mm',
    'OORoleSet+ObjCBridge.mm',
    'OOShipGroup.mm',
    'OOShipGroup+ObjCBridge.mm',
    'OOShipLibraryDescriptions.mm',
    'OOShipRegistry.mm',
    'OOShipRegistry+ObjCBridge.mm',
    'OOSkyDrawable.mm',
    'OOSoundSource.mm',
    'OOSoundSource+ObjCBridge.mm',
    'OOSoundSourcePool.mm',
    'OOSoundSourcePool+ObjCBridge.mm',
    'OOStringExpander.mm',
    'OOStringParsing.mm',
    'OOSystemDescriptionManager.mm',
    'OOSystemDescriptionManager+ObjCBridge.mm',
    'OOTextureScaling.mm',
    'OOTextureSprite.mm',
    'OOTextureSprite+ObjCBridge.mm',
    'OOTrumble.mm',
    'OOTrumble+ObjCBridge.mm',
    'OOVector.mm',
    'OOVector+ObjCBridge.mm',
    'OOVoxel.c',
    'OOWeakReference.mm',
    'OOWeakReference+ObjCBridge.mm',
    'OOWeakSet.mm',
    'OOWeakSet+ObjCBridge.mm',
    'OOXMLExtensions.mm',
    'Octree.mm',
    'Octree+ObjCBridge.mm',
    'ResourceManager.mm',
    'Universe.mm',
    'legacy_random.c',
)

oolite_includes += include_directories('.')

# Enter child subdirectories
subdir('Debug')
subdir('Entities')
subdir('Materials')
subdir('MiniZip')
subdir('OXPVerifier')
subdir('Scripting')
subdir('Tables')
