# Generated Meson configuration for sub-module: Core

oolite_sources += files(
    'AI.mm',
    'AI+FoundationBridge.mm',
    'AIGraphViz.mm',
    'CollisionRegion.mm',
    'GameController.mm',
    'GuiDisplayGen.mm',
    'GuiDisplayGen+FoundationBridge.mm',
    'HeadUpDisplay.mm',
    'HeadUpDisplay+FoundationBridge.mm',
    'NSDataOOExtensions.mm',
    'NSDictionaryOOExtensions.mm',
    'NSFileManagerOOExtensions.mm',
    'NSMutableDictionaryOOExtensions.mm',
    'NSNumberOOExtensions.mm',
    'NSObjectOOExtensions.mm',
    'NSScannerOOExtensions.mm',
    'NSStringOOExtensions.mm',
    'NSUserDefaults+Override.mm',
    'OOALBufferedSound.mm',
    'OOALMusic.mm',
    'OOALSound.mm',
    'OOALSoundChannel.mm',
    'OOALSoundDecoder.mm',
    'OOALSoundMixer.mm',
    'OOALStreamedSound.mm',
    'OOAsyncQueue.mm',
    'OOAsyncWorkManager.mm',
    'OOCPUInfo.mm',
    'OOCache.mm',
    'OOCacheManager.mm',
    'OOCacheManager+FoundationBridge.mm',
    'OOCharacter.mm',
    'OOCocoa.mm',
    'OOCollectionExtractors.mm',
    'OOColor.mm',
    'OOColor+FoundationBridge.mm',
    'OOCommodities.mm',
    'OOCommodityMarket.mm',
    'OOCommodityMarket+FoundationBridge.mm',
    'OOConstToString.mm',
    'OOConvertCubeMapToLatLong.mm',
    'OOConvertSystemDescriptions.mm',
    'OOCrosshairs.mm',
    'OODebugGLDrawing.mm',
    'OODeepCopy.mm',
    'OODrawable.mm',
    'OOEncodingConverter.mm',
    'OOEntityFilterPredicate.mm',
    'OOEnumerationShuffle.mm',
    'OOEquipmentType.mm',
    'OOExcludeObjectEnumerator.mm',
    'OOFilteringEnumerator.mm',
    'OOGraphicsResetManager.mm',
    'OOHPVector.mm',
    'OOHPVector+FoundationBridge.mm',
    'OOIsNumberLiteral.mm',
    'OOJoystickManager.mm',
    'OOJoystickProfile.mm',
    'OOLogHeader.mm',
    'OOLogOutputHandler.mm',
    'OOLogging.mm',
    'OOLogging+FoundationBridge.mm',
    'OOMatrix.mm',
    'OOMesh.mm',
    'OOMeshToOctreeConverter.mm',
    'OOMouseInteractionMode.mm',
    'OOMusicController.mm',
    'OOOXZManager.mm',
    'OOObjectGNUstepBridge.mm',
    'OOOpenALController.mm',
    'OOOpenGL.mm',
    'OOOpenGL+FoundationBridge.mm',
    'OOOpenGLExtensionManager.mm',
    'OOOpenGLMatrixManager.mm',
    'OOOpenGLStateManager.mm',
    'OOPListParsing.mm',
    'OOPListParsing+FoundationBridge.mm',
    'OOPlanetData.c',
    'OOPlanetDrawable.mm',
    'OOPolygonSprite.mm',
    'OOPriorityQueue.mm',
    'OOProbabilisticTextureManager.mm',
    'OOProbabilitySet.mm',
    'OOProfilingStopwatch.mm',
    'OOQuaternion.mm',
    'OORegExpMatcher.mm',
    'OORoleSet.mm',
    'OOShipGroup.mm',
    'OOShipLibraryDescriptions.mm',
    'OOShipRegistry.mm',
    'OOShipRegistry+FoundationBridge.mm',
    'OOSkyDrawable.mm',
    'OOSoundSource.mm',
    'OOSoundSourcePool.mm',
    'OOSpatialReference.mm',
    'OOStringExpander.mm',
    'OOStringParsing.mm',
    'OOStringParsing+FoundationBridge.mm',
    'OOSystemDescriptionManager.mm',
    'OOSystemDescriptionManager+FoundationBridge.mm',
    'OOTextureScaling.mm',
    'OOTextureSprite.mm',
    'OOTrumble.mm',
    'OOVector.mm',
    'OOVoxel.mm',
    'OOWeakReference.mm',
    'OOWeakSet.mm',
    'OOXMLExtensions.mm',
    'Octree.mm',
    'OldSchoolPropertyListWriting.mm',
    'ResourceManager.mm',
    'ResourceManager+FoundationBridge.mm',
    'TextureStore.mm',
    'Universe.mm',
    'legacy_random.c',
)

if host_os != 'darwin'
    oolite_sources += files(
        'NSBundle+Override.mm',
        'NSUserDefaults+Override.mm',
    )
endif

oolite_includes += include_directories('.')

# Enter child subdirectories
subdir('Debug')
subdir('Entities')
subdir('Materials')
subdir('MiniZip')
subdir('OXPVerifier')
subdir('Scripting')
subdir('Tables')
