# Generated Meson configuration for sub-module: SDL

oolite_sources += files(
    'Comparison.mm',
    'GameController+SDLFullScreen.mm',
    'MyOpenGLView.mm',
    'MyOpenGLView+FoundationBridge.mm',
    'MyOpenGLView+Input.mm',
    'OOSDLJoystickManager.mm',
    'main.mm',
)

oolite_includes += include_directories('.')

# Enter child subdirectories
subdir('EXRSnapshotSupport')
subdir('OOResourcesWin')
