# Generated Meson configuration for sub-module: Scripting

oolite_sources += files(
    'EntityOOJavaScriptExtensions.mm',
    'OOConstToJSString.mm',
    'OOJSCall.mm',
    'OOJSClock.mm',
    'OOJSDock.mm',
    'OOJSEngineDebuggerHelpers.mm',
    'OOJSEngineTimeManagement.mm',
    'OOJSEntity.mm',
    'OOJSEquipmentInfo.mm',
    'OOJSExhaustPlume.mm',
    'OOJSFlasher.mm',
    'OOJSFont.mm',
    'OOJSFrameCallbacks.mm',
    'OOJSFunction.mm',
    'OOJSGlobal.mm',
    'OOJSGuiScreenKeyDefinition.mm',
    'OOJSInterfaceDefinition.mm',
    'OOJSManifest.mm',
    'OOJSMission.mm',
    'OOJSMissionVariables.mm',
    'OOJSOolite.mm',
    'OOJSPlanet.mm',
    'OOJSPlayer.mm',
    'OOJSPlayerShip.mm',
    'OOJSPopulatorDefinition.mm',
    'OOJSQuaternion.mm',
    'OOJSScript.mm',
    'OOJSShip.mm',
    'OOJSShipGroup.mm',
    'OOJSSound.mm',
    'OOJSSoundSource.mm',
    'OOJSSpecialFunctions.mm',
    'OOJSStation.mm',
    'OOJSSun.mm',
    'OOJSSystem.mm',
    'OOJSSystemInfo.mm',
    'OOJSTimer.mm',
    'OOJSVector.mm',
    'ooscript/JSEngine_spidermonkey.cpp',
    'OOJSVisualEffect.mm',
    'OOJSWaypoint.mm',
    'OOJSWorldScripts.mm',
    'OOJSWormhole.mm',
    'OOJavaScriptEngine.mm',
    'OOLegacyScriptWhitelist.mm',
    'OOPListScript.mm',
    'OOScript.mm',
    'OOScriptTimer.mm',
)

oolite_includes += include_directories('.')

