# Generated Meson configuration for sub-module: Scripting

oolite_sources += files(
    'EntityOOJavaScriptExtensions.m',
    'OOConstToJSString.m',
    'OOJSCall.m',
    'OOJSClock.mm',
    'OOJSDock.mm',
    'OOJSEngineDebuggerHelpers.mm',
    'OOJSEngineTimeManagement.m',
    'OOJSEntity.m',
    'OOJSEquipmentInfo.mm',
    'OOJSExhaustPlume.mm',
    'OOJSFlasher.mm',
    'OOJSFont.mm',
    'OOJSFrameCallbacks.m',
    'OOJSFunction.m',
    'OOJSGlobal.mm',
    'OOJSGuiScreenKeyDefinition.mm',
    'OOJSInterfaceDefinition.m',
    'OOJSManifest.m',
    'OOJSMission.mm',
    'OOJSMissionVariables.mm',
    'OOJSOolite.m',
    'OOJSPlanet.mm',
    'OOJSPlayer.mm',
    'OOJSPlayerShip.mm',
    'OOJSPopulatorDefinition.mm',
    'OOJSQuaternion.mm',
    'OOJSScript.m',
    'OOJSShip.m',
    'OOJSShipGroup.mm',
    'OOJSSound.mm',
    'OOJSSoundSource.mm',
    'OOJSSpecialFunctions.m',
    'OOJSStation.mm',
    'OOJSSun.mm',
    'OOJSSystem.m',
    'OOJSSystemInfo.mm',
    'OOJSTimer.mm',
    'OOJSVector.mm',
    'ooscript/JSEngine_spidermonkey.cpp',
    'OOJSVisualEffect.mm',
    'OOJSWaypoint.mm',
    'OOJSWorldScripts.mm',
    'OOJSWormhole.mm',
    'OOJavaScriptEngine.m',
    'OOLegacyScriptWhitelist.m',
    'OOPListScript.m',
    'OOScript.m',
    'OOScriptTimer.m',
)

oolite_includes += include_directories('.')

