# Generated Meson configuration for sub-module: OXPVerifier

oolite_sources += files(
    'OOAIStateMachineVerifierStage.mm',
    'OOCheckDemoShipsPListVerifierStage.mm',
    'OOCheckEquipmentPListVerifierStage.mm',
    'OOCheckJSSyntaxVerifierStage.mm',
    'OOCheckPListSyntaxVerifierStage.mm',
    'OOCheckRequiresPListVerifierStage.mm',
    'OOCheckShipDataPListVerifierStage.mm',
    'OOCheckShipDataPListVerifierStage+ObjCBridge.mm',
    'OOFileScannerVerifierStage.mm',
    'OOFileScannerVerifierStage+ObjCBridge.mm',
    'OOModelVerifierStage.mm',
    'OOOXPVerifier.mm',
    'OOOXPVerifierStage.mm',
    'OOOXPVerifierStage+ObjCBridge.mm',
    'OOPListSchemaVerifier.mm',
    'OOPListSchemaVerifier+ObjCBridge.mm',
    'OOTextureVerifierStage.mm',
    'OOTextureVerifierStage+ObjCBridge.mm',
)

oolite_includes += include_directories('.')

