/*	test_localized_compare.cpp
	oo::str::localizedCompare (oofnd/String.hpp, bead oo-r4d6) against -[NSString localizedCompare:]
	of GNUstep base 1.31.1.

	localized_compare_table.inc was generated by a throwaway Objective-C probe linked against
	gnustep-base: for every ordered pair of its words it recorded the sign of
	[words[i] localizedCompare:words[j]], with [NSLocale currentLocale] = kLocalizedCompareLocale.
	The words cover case, digits and version strings, punctuation and spaces, accents (precomposed
	and combining), ligatures, non-Latin scripts and the manifest categories OOOXZManager sorts.
	To extend it, rebuild that probe with more words and replace the table; do not hand-edit it.
*/

#include "oofnd/String.hpp"

#include "oo_test.hpp"

#include "localized_compare_table.inc"

#include <algorithm>
#include <cstddef>
#include <string>
#include <vector>

namespace {

constexpr std::size_t kWords = sizeof(kLocalizedCompareWords) / sizeof(kLocalizedCompareWords[0]);
static_assert(sizeof(kLocalizedCompareSigns) / sizeof(kLocalizedCompareSigns[0]) == kWords);

int sign(int v)
{
	return v < 0 ? -1 : (v > 0 ? 1 : 0);
}

} // namespace

OO_TEST(every_pair_matches_gnustep)
{
	OO_CHECK(kWords >= 60u);
	std::size_t mismatches = 0;
	for (std::size_t i = 0; i < kWords; ++i)
	{
		for (std::size_t j = 0; j < kWords; ++j)
		{
			const int got = sign(oo::str::localizedCompare(kLocalizedCompareWords[i], kLocalizedCompareWords[j], kLocalizedCompareLocale));
			if (got != kLocalizedCompareSigns[i][j])
			{
				++mismatches;
				OO_CHECK_EQ(got, kLocalizedCompareSigns[i][j]);
			}
		}
	}
	OO_CHECK_EQ(mismatches, 0u);
}

OO_TEST(readable_orderings)
{
	// The case the manifest sort depends on: lower before upper, both before the next letter.
	OO_CHECK(oo::str::localizedCompare("a", "A", "en_US") < 0);
	OO_CHECK(oo::str::localizedCompare("A", "b", "en_US") < 0);
	OO_CHECK(oo::str::localizedCompare("Zz", "zz", "en_US") > 0);
	OO_CHECK_EQ(oo::str::localizedCompare("Ships", "Ships", "en_US"), 0);
	// ... where the literal order (compare) disagrees.
	OO_CHECK(oo::str::compare("A", "b") < 0);
	OO_CHECK(oo::str::compare("a", "B") > 0);
	OO_CHECK(oo::str::localizedCompare("a", "B", "en_US") < 0);
}

OO_TEST(sorting_matches_the_table)
{
	// A sort by localizedCompare agrees with the order the GNUstep signs imply.
	std::vector<std::size_t> order(kWords);
	for (std::size_t i = 0; i < kWords; ++i) order[i] = i;
	std::stable_sort(order.begin(), order.end(), [](std::size_t x, std::size_t y) {
		return oo::str::localizedCompare(kLocalizedCompareWords[x], kLocalizedCompareWords[y], kLocalizedCompareLocale) < 0;
	});
	for (std::size_t k = 1; k < kWords; ++k)
	{
		OO_CHECK(kLocalizedCompareSigns[order[k - 1]][order[k]] <= 0);
	}
}

OO_TEST(default_locale_form_uses_icus_default)
{
	for (std::size_t i = 0; i < kWords; ++i)
	{
		OO_CHECK_EQ(sign(oo::str::localizedCompare(kLocalizedCompareWords[i], "m")),
					sign(oo::str::localizedCompare(kLocalizedCompareWords[i], "m", uloc_getDefault())));
	}
}

OO_TEST_MAIN()
