/*	test_unicode_file_decode.cpp
	oo::str::decodeUnicodeFile (oofnd/String.hpp, bead oo-3rb.62) against GNUstep base 1.31.1.

	+[NSString stringWithContentsOfUnicodeFile:] (NSStringOOExtensions) decides between UTF-16,
	UTF-8 and ISO Latin-1 itself and hands the bytes to -stringWithCharacters:length: or
	-initWithBytes:length:encoding:, whose mark handling and UTF-8 validation are GNUstep's. The
	expectations were captured from a throwaway Objective-C probe linked against gnustep-base
	1.31.1 that ran the category's body (with the corrected length - 3, see String.hpp) over the
	same inputs and printed, per input, "<units>:" and " %04X" per UTF-16 unit, the line units()
	builds here. The corpus is generated by FileCorpus below, byte for byte what the probe read;
	its digest equals GNUstep's exactly when every one of the 40,000 lines matches.
*/

// The header must survive OOCocoa.h's true/false macros and hand them back (proposed ADR-0028).
#define true						1
#define false						0
#include "oofnd/String.hpp"
#include <type_traits>
static_assert(std::is_same_v<decltype(true), int>, "String.hpp must restore OOCocoa.h's true macro");
#undef true
#undef false

#include "oo_test.hpp"

#include <cstdint>
#include <cstdio>
#include <initializer_list>
#include <iterator>
#include <string>
#include <vector>

namespace {

std::string units(const std::string& utf8)
{
	const std::u16string u = oo::utf8ToUtf16(utf8);
	std::string line = std::to_string(u.size()) + ":";
	char buf[8];
	for (char16_t c : u)
	{
		std::snprintf(buf, sizeof buf, " %04X", unsigned(c));
		line += buf;
	}
	return line;
}

std::string decode(std::initializer_list<std::uint8_t> bytes)
{
	const std::vector<std::uint8_t> b(bytes);
	return units(oo::str::decodeUnicodeFile(b.data(), b.size()));
}

struct FileCorpus
{
	std::uint64_t s;
	explicit FileCorpus(std::uint64_t seed) : s(seed) {}
	std::uint32_t next()
	{
		s ^= s << 13;
		s ^= s >> 7;
		s ^= s << 17;
		return static_cast<std::uint32_t>(s >> 32);
	}
	// Byte strings led by any mix of byte-order marks, then bytes biased towards UTF-8 lead and
	// continuation bytes, BOM halves, surrogate halves and overlong/out-of-range leads, or a
	// well-formed UTF-8 run of interesting code points.
	std::vector<std::uint8_t> file()
	{
		static constexpr std::uint8_t kPool[] = {0x00, 0x41, 0x42, 0xEF, 0xBB, 0xBF, 0xFE, 0xFF, 0xC3, 0xA9,
			0xED, 0xA0, 0xB0, 0x80, 0x9F, 0xF0, 0x90, 0xF4, 0x8F, 0xE0, 0xC0, 0xC1, 0xC2, 0xD8, 0xDC, 0x3F,
			0x0A, 0x20, 0xF5, 0xF8, 0xBE, 0xBC, 0x7F, 0x81};
		static constexpr std::uint8_t kMarks[][2] = {{0xEF, 0xBB}, {0xFF, 0xFE}, {0xFE, 0xFF}};
		std::vector<std::uint8_t> b;
		for (std::uint32_t m = next() % 4; m > 0; --m)
		{
			const auto& mark = kMarks[next() % 3];
			b.push_back(mark[0]);
			b.push_back(mark[1]);
			if (mark[0] == 0xEF) b.push_back(0xBF);
		}
		if (next() % 3 == 0)
		{
			static constexpr char32_t kPoints[] = {0x41, 0xE9, 0xFEFF, 0xFFFE, 0x10000, 0x10FFFF, 0x800, 0xD7FF, 0xE000, 0};
			for (std::uint32_t k = next() % 5; k > 0; --k)
			{
				const char32_t c = kPoints[next() % 10];
				if (c < 0x80) b.push_back(std::uint8_t(c));
				else if (c < 0x800) { b.push_back(std::uint8_t(0xC0 | (c >> 6))); b.push_back(std::uint8_t(0x80 | (c & 0x3F))); }
				else if (c < 0x10000) { b.push_back(std::uint8_t(0xE0 | (c >> 12))); b.push_back(std::uint8_t(0x80 | ((c >> 6) & 0x3F))); b.push_back(std::uint8_t(0x80 | (c & 0x3F))); }
				else { b.push_back(std::uint8_t(0xF0 | (c >> 18))); b.push_back(std::uint8_t(0x80 | ((c >> 12) & 0x3F))); b.push_back(std::uint8_t(0x80 | ((c >> 6) & 0x3F))); b.push_back(std::uint8_t(0x80 | (c & 0x3F))); }
			}
		}
		for (std::uint32_t n = next() % 13; n > 0; --n)
		{
			b.push_back(next() % 5 == 0 ? std::uint8_t(next()) : kPool[next() % std::size(kPool)]);
		}
		return b;
	}
};

} // namespace

OO_TEST(utf16FilesKeepTheCategorysByteOrderAndGNUstepsMarkHandling)
{
	// Units after the first mark are little-endian whichever mark it was.
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0x41, 0x00}), "1: 0041");
	OO_CHECK_EQ(decode({0xFE, 0xFF, 0x41, 0x00}), "1: 0041");
	OO_CHECK_EQ(decode({0xFE, 0xFF, 0x00, 0x41}), "1: 4100");
	// -stringWithCharacters: drops a leading U+FEFF, drops a leading U+FFFE and swaps the rest;
	// GNUstep applies that twice.
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0xFF, 0xFE, 0x41, 0x00}), "1: 0041");
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0xFE, 0xFF, 0x41, 0x00}), "1: 4100");
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0xFF, 0xFE, 0xFF, 0xFE, 0x41, 0x00}), "1: 0041");
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0xFF, 0xFE, 0xFF, 0xFE, 0xFF, 0xFE, 0x41, 0x00}), "2: FEFF 0041");
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0xFE, 0xFF, 0xFF, 0xFE, 0x00, 0x41}), "1: 4100");
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0xFF, 0xFE, 0xFE, 0xFF, 0x41, 0x00}), "1: 4100");
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0x41, 0x00, 0xFF, 0xFE, 0x42, 0x00}), "3: 0041 FEFF 0042");
	OO_CHECK_EQ(decode({0xFF, 0xFE}), "0:");
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0x00, 0xD8}), "1: D800");
	OO_CHECK_EQ(decode({0xFF, 0xFE, 0xFF, 0xFF}), "1: FFFF");
}

OO_TEST(utf8FilesSkipTheBomAndValidateStrictly)
{
	OO_CHECK_EQ(decode({}), "0:");
	OO_CHECK_EQ(decode({0x41}), "1: 0041");
	OO_CHECK_EQ(decode({0x00}), "1: 0000");
	OO_CHECK_EQ(decode({0xC3, 0xA9}), "1: 00E9");
	OO_CHECK_EQ(decode({0xEF, 0xBB, 0xBF, 0x41}), "1: 0041");
	OO_CHECK_EQ(decode({0xEF, 0xBB, 0xBF}), "0:");
	OO_CHECK_EQ(decode({0xEF, 0xBB, 0xBF, 0x00}), "1: 0000");
	// After the category's own skip GNUstep drops up to two more leading U+FEFF, and never swaps.
	OO_CHECK_EQ(decode({0xEF, 0xBB, 0xBF, 0xEF, 0xBB, 0xBF, 0xEF, 0xBB, 0xBF, 0x41}), "1: 0041");
	OO_CHECK_EQ(decode({0xEF, 0xBB, 0xBF, 0xEF, 0xBB, 0xBF, 0xEF, 0xBB, 0xBF, 0xEF, 0xBB, 0xBF, 0x41}), "2: FEFF 0041");
	OO_CHECK_EQ(decode({0xEF, 0xBB, 0xBF, 0xEF, 0xBB, 0xBF, 0xEF, 0xBF, 0xBE, 0x41}), "2: FFFE 0041");
	OO_CHECK_EQ(decode({0xEF, 0xBF, 0xBE, 0x41}), "2: FFFE 0041");
	OO_CHECK_EQ(decode({0x41, 0xEF, 0xBB, 0xBF, 0x42}), "3: 0041 FEFF 0042");
	OO_CHECK_EQ(decode({0xF0, 0x90, 0x80, 0x80}), "2: D800 DC00");
	OO_CHECK_EQ(decode({0xF4, 0x80, 0x80, 0x80}), "2: DBC0 DC00");
	// The corrected length: exactly the bytes after the BOM (the category read six past them).
	OO_CHECK_EQ(decode({0xEF, 0xBB, 0xBF, 0xE9}), "1: 00E9");
}

OO_TEST(invalidUtf8FallsBackToLatin1)
{
	OO_CHECK_EQ(decode({0xE9}), "1: 00E9");
	OO_CHECK_EQ(decode({0xC3}), "1: 00C3");
	OO_CHECK_EQ(decode({0xED, 0xA0, 0x80}), "3: 00ED 00A0 0080");	// an encoded surrogate
	OO_CHECK_EQ(decode({0xC0, 0x80}), "2: 00C0 0080");				// overlong
	OO_CHECK_EQ(decode({0xE0, 0x80, 0x8F}), "3: 00E0 0080 008F");
	OO_CHECK_EQ(decode({0xF0, 0x8F, 0x80, 0x80}), "4: 00F0 008F 0080 0080");
	OO_CHECK_EQ(decode({0xF4, 0x90, 0x80, 0x80}), "4: 00F4 0090 0080 0080");	// above U+10FFFF
	OO_CHECK_EQ(decode({0xF8, 0x80, 0x80, 0x80, 0x80}), "5: 00F8 0080 0080 0080 0080");
	OO_CHECK_EQ(decode({0xFF, 0xFF}), "2: 00FF 00FF");			// even length, not a mark
	OO_CHECK_EQ(decode({0xEF, 0xBB, 0xBF, 0xC3}), "1: 00C3");		// Latin-1 of the bytes after the BOM
	OO_CHECK_EQ(decode({0xEF, 0xBB, 0xBF, 0xFF, 0xFE, 0x41, 0x00}), "4: 00FF 00FE 0041 0000");
}

OO_TEST(corpusMatchesGNUstep)
{
	FileCorpus corpus(0x62);
	std::uint64_t h = 14695981039346656037ULL;
	for (int i = 0; i < 40000; ++i)
	{
		const std::vector<std::uint8_t> b = corpus.file();
		for (unsigned char c : units(oo::str::decodeUnicodeFile(b.data(), b.size())) + "\n")
		{
			h = (h ^ c) * 1099511628211ULL;
		}
	}
	OO_CHECK_EQ(h, 0x999d45242cdbb86eULL);
}

OO_TEST(dataOverloadIsTheSame)
{
	const oo::Data d(reinterpret_cast<const std::uint8_t*>("\xEF\xBB\xBF" "abc"), 6);
	OO_CHECK_EQ(oo::str::decodeUnicodeFile(d), std::string("abc"));
}

OO_TEST_MAIN()
