# Generated Meson configuration for sub-module: Materials

oolite_sources += files(
    'OOBasicMaterial.mm',
    'OOCombinedEmissionMapGenerator.mm',
    'OOConcreteTexture.mm',
    'OODefaultShaderSynthesizer.mm',
    'OOMaterial.mm',
    'OOMaterialConvenienceCreators.mm',
    'OOMaterialSpecifier.mm',
    'OOMaterialSpecifier+FoundationBridge.mm',
    'OOMultiTextureMaterial.mm',
    'OONullTexture.mm',
    'OOPNGTextureLoader.mm',
    'OOPixMap.mm',
    'OOPixMapChannelOperations.mm',
    'OOPixMapTextureLoader.mm',
    'OOPlanetTextureGenerator.mm',
    'OOShaderMaterial.mm',
    'OOShaderProgram.mm',
    'OOShaderUniform.mm',
    'OOShaderUniformMethodType.mm',
    'OOSingleTextureMaterial.mm',
    'OOStandaloneAtmosphereGenerator.mm',
    'OOTexture.mm',
    'OOTexture+FoundationBridge.mm',
    'OOTextureGenerator.mm',
    'OOTextureLoader.mm',
)

oolite_includes += include_directories('.')

