# Generated Meson configuration for sub-module: Materials

oolite_sources += files(
    'OOBasicMaterial.mm',
    'OOBasicMaterial+ObjCBridge.mm',
    'OOCombinedEmissionMapGenerator.mm',
    'OOCombinedEmissionMapGenerator+ObjCBridge.mm',
    'OOConcreteTexture.mm',
    'OOConcreteTexture+ObjCBridge.mm',
    'OODefaultShaderSynthesizer.mm',
    'OODefaultShaderSynthesizer+ObjCBridge.mm',
    'OOMaterial.mm',
    'OOMaterial+ObjCBridge.mm',
    'OOMaterialConvenienceCreators.mm',
    'OOMaterialConvenienceCreators+ObjCBridge.mm',
    'OOMaterialSpecifier.mm',
    'OOMultiTextureMaterial.mm',
    'OONullTexture.mm',
    'OONullTexture+ObjCBridge.mm',
    'OOPNGTextureLoader.mm',
    'OOPixMap.mm',
    'OOPixMapChannelOperations.mm',
    'OOPixMapTextureLoader.mm',
    'OOPlanetTextureGenerator.mm',
    'OOShaderMaterial.mm',
    'OOShaderProgram.mm',
    'OOShaderProgram+ObjCBridge.mm',
    'OOShaderUniform.mm',
    'OOShaderUniform+ObjCBridge.mm',
    'OOShaderUniformMethodType.mm',
    'OOSingleTextureMaterial.mm',
    'OOStandaloneAtmosphereGenerator.mm',
    'OOTexture.mm',
    'OOTexture+ObjCBridge.mm',
    'OOTextureGenerator.mm',
    'OOTextureGenerator+ObjCBridge.mm',
    'OOTextureLoader.mm',
    'OOTextureLoader+ObjCBridge.mm',
)

oolite_includes += include_directories('.')

