/*	test_OOJSCallEntityMethods.mm
	Unit tests for callObjC()'s entity name table (src/Core/Scripting/OOJSCallEntityMethods.h,
	generated by tools/gen-callobjc-entity-table.py): bead oo-9ht.44, ADR-0056 amendment oo-9ht.44.

	The oracle is the signature matcher callObjC() used for an entity's object before the table
	(OOJSCall.mm's GetMethodType(), whose templates were the deleted bridge's template methods:
	void/void, void/const std::string &, oo::PList/const std::string &, oo::PList/void,
	else the shader uniform type of the return type). Its safe set on the root facade's own methods
	(the class Entity, with every category; not its superclasses) is the selectors it matched with
	no argument or with one of the two string templates, less the lifetime and root-protocol
	names and the compiler's .cxx_construct/.cxx_destruct. The table must list exactly that set, and
	each row must classify its method as the matcher did. The facade is the real one, so the test
	links the whole game but main (['*']).
	Run: bash tools/check-core-tests.sh
*/

#import "OOJSCallEntityMethods.h"
#import "OOShaderUniformMethodType.h"

#include "oo_test.hpp"

#include <objc/runtime.h>
#include <cstdlib>
#include <cstring>
#include <iterator>
#include <map>
#include <optional>
#include <set>
#include <string>


// main.mm defines the debug flags, and the test has its own main.
#ifndef NDEBUG
uint32_t gDebugFlags = 0;
#endif


namespace {

// The names the generator leaves out (tools/gen-callobjc-entity-table.py EXCLUDED).
const std::set<std::string> kExcluded =
{
	"init", "dealloc", "finalize", "retain", "release", "autorelease", "retainCount", "copy",
	"mutableCopy", "self", "class", "superclass", "hash", "description", "debugDescription",
	"isProxy", "zone",
};


struct OracleRow
{
	OOJSCallEntityMethodForm	form;
	OOShaderUniformType			type;	// a Typed row's
};


bool SameEncoding(char *copied, const char *expected)
{
	bool result = (copied != nullptr && std::strcmp(copied, expected) == 0);
	std::free(copied);
	return result;
}


// The template signature returnType (self, _cmd[, argument]), as the template class's methods had it.
bool Matches(Method method, const char *returnType, const char *argument)
{
	const char *arguments[] = { @encode(id), @encode(SEL), argument };
	unsigned count = method_getNumberOfArguments(method);
	if (count != (argument != nullptr ? 3u : 2u))  return false;
	if (!SameEncoding(method_copyReturnType(method), returnType))  return false;
	for (unsigned i = 0; i < count; i++)
	{
		if (!SameEncoding(method_copyArgumentType(method, i), arguments[i]))  return false;
	}
	return true;
}


// The matcher's classification of a method in its safe set; nullopt outside it.
std::optional<OracleRow> Oracle(Method method)
{
	if (Matches(method, @encode(void), nullptr))  return OracleRow{ OOJSCallEntityMethodForm::VoidVoid, kOOShaderUniformTypeInvalid };
	if (Matches(method, @encode(void), @encode(const std::string &)))  return OracleRow{ OOJSCallEntityMethodForm::VoidString, kOOShaderUniformTypeInvalid };
	if (Matches(method, @encode(oo::PList), @encode(const std::string &)))  return OracleRow{ OOJSCallEntityMethodForm::PListString, kOOShaderUniformTypeInvalid };
	if (Matches(method, @encode(oo::PList), nullptr))  return OracleRow{ OOJSCallEntityMethodForm::PListVoid, kOOShaderUniformTypeInvalid };
	if (method_getNumberOfArguments(method) != 2)  return std::nullopt;	// called with its arguments missing
	return OracleRow{ OOJSCallEntityMethodForm::Typed, OOShaderUniformTypeFromMethod(method) };
}


std::map<std::string, OracleRow> OracleSafeSet()
{
	std::map<std::string, OracleRow> result;
	unsigned count = 0;
	Method *methods = class_copyMethodList([Entity class], &count);
	for (unsigned i = 0; i < count; i++)
	{
		const std::string name = sel_getName(method_getName(methods[i]));
		if (name.empty() || name[0] == '.')  continue;	// .cxx_construct / .cxx_destruct
		std::string bare = name;
		if (!bare.empty() && bare.back() == ':')  bare.pop_back();
		if (kExcluded.contains(bare))  continue;
		if (std::optional<OracleRow> row = Oracle(methods[i]))  result[name] = *row;
	}
	std::free(methods);
	return result;
}

}	// namespace


OO_TEST(tableIsTheMatchersSafeSet)
{
	@autoreleasepool
	{
		const std::map<std::string, OracleRow> oracle = OracleSafeSet();
		std::map<std::string, const OOJSCallEntityMethodRow *> table;
		for (const OOJSCallEntityMethodRow &row : kOOJSCallEntityMethods)  table[row.name] = &row;
		OO_CHECK_EQ(table.size(), std::size(kOOJSCallEntityMethods));	// no name twice
		OO_CHECK(oracle.size() > 400);	// the facade's forwarders and by-name categories

		std::string missing, extra, different;
		for (const auto &[name, row] : oracle)
		{
			auto found = table.find(name);
			if (found == table.end())  { missing += " " + name;  continue; }
			const OOJSCallEntityMethodRow &entry = *found->second;
			bool same = (entry.form == row.form);
			if (same && row.form == OOJSCallEntityMethodForm::Typed)  same = (OOShaderUniformTypeFromEncoding(entry.encoding) == row.type);
			if (!same)  different += " " + name;
		}
		for (const auto &[name, entry] : table)
		{
			if (!oracle.contains(name))  extra += " " + name;
		}
		OO_CHECK_EQ(missing, std::string());
		OO_CHECK_EQ(extra, std::string());
		OO_CHECK_EQ(different, std::string());
	}
}


// The safe set leaves out what callObjC() could not call safely: lifetime and root-protocol
// names, and every selector with an argument but the two string templates.
OO_TEST(tableLeavesOutUnsafeNames)
{
	std::set<std::string> names;
	for (const OOJSCallEntityMethodRow &row : kOOJSCallEntityMethods)  names.insert(row.name);
	for (const char *name : { "init", "dealloc", "retain", "release", "autorelease", "copy", "self", "class", "hash", "description", "respondsToSelector:", "isKindOfClass:", "initWithCxxEntity:" })
	{
		OO_CHECK(!names.contains(name));
	}
	for (const OOJSCallEntityMethodRow &row : kOOJSCallEntityMethods)
	{
		const bool takesString = (row.form == OOJSCallEntityMethodForm::VoidString || row.form == OOJSCallEntityMethodForm::PListString);
		const bool endsWithColon = (std::strlen(row.name) > 0 && row.name[std::strlen(row.name) - 1] == ':');
		OO_CHECK(takesString == endsWithColon);
		OO_CHECK((row.form == OOJSCallEntityMethodForm::Typed) == (row.encoding != nullptr));
	}
}


OO_TEST_MAIN()
