# Generated Meson configuration for sub-module: Entities

oolite_sources += files(
    'DockEntity.mm',
    'DockEntity+ObjCBridge.mm',
    'DustEntity.mm',
    'Entity.mm',
    'Entity+ObjCBridge.mm',
    'EntityShaderBindings.mm',
    'EntityShaderBindings+ObjCBridge.mm',
    'OOBreakPatternEntity.mm',
    'OOECMBlastEntity.mm',
    'OOEntityWithDrawable.mm',
    'OOEntityWithDrawable+ObjCBridge.mm',
    'OOExhaustPlumeEntity.mm',
    'OOExplosionCloudEntity.mm',
    'OOFlashEffectEntity.mm',
    'OOFlashEffectEntity+ObjCBridge.mm',
    'OOFlasherEntity.mm',
    'OOLaserShotEntity.mm',
    'OOLaserShotEntity+ObjCBridge.mm',
    'OOLightParticleEntity.mm',
    'OOLightParticleEntity+ObjCBridge.mm',
    'OOParticleSystem.mm',
    'OOPlanetEntity.mm',
    'OOPlanetEntity+ObjCBridge.mm',
    'OOPlasmaBurstEntity.mm',
    'OOPlasmaShotEntity.mm',
    'OOQuiriumCascadeEntity.mm',
    'OOQuiriumCascadeEntity+ObjCBridge.mm',
    'OORingEffectEntity.mm',
    'OOSparkEntity.mm',
    'OOSunEntity.mm',
    'OOSunEntity+ObjCBridge.mm',
    'OOVisualEffectEntity.mm',
    'OOVisualEffectEntity+ObjCBridge.mm',
    'OOWaypointEntity.mm',
    'OOWaypointEntity+ObjCBridge.mm',
    'PlayerEntity.mm',
    'PlayerEntity+ObjCBridge.mm',
    'PlayerEntityContracts.mm',
    'PlayerEntityControls.mm',
    'PlayerEntityKeyMapper.mm',
    'PlayerEntityLegacyScriptEngine.mm',
    'PlayerEntityLoadSave.mm',
    'PlayerEntityScriptMethods.mm',
    'PlayerEntitySound.mm',
    'PlayerEntityStickMapper.mm',
    'PlayerEntityStickProfile.mm',
    'ProxyPlayerEntity.mm',
    'ShipEntity.mm',
    'ShipEntity+ObjCBridge.mm',
    'ShipEntityAI.mm',
    'ShipEntityLoadRestore.mm',
    'ShipEntityScriptMethods.mm',
    'SkyEntity.mm',
    'SkyEntity+ObjCBridge.mm',
    'StationEntity.mm',
    'StationEntity+ObjCBridge.mm',
    'WormholeEntity.mm',
    'WormholeEntity+ObjCBridge.mm',
)

oolite_includes += include_directories('.')

