# Generated Meson configuration for sub-module: Entities

oolite_sources += files(
    'DockEntity.mm',
    'DustEntity.mm',
    'Entity.mm',
    'OOBreakPatternEntity.mm',
    'OOECMBlastEntity.mm',
    'OOEntityWithDrawable.mm',
    'OOExhaustPlumeEntity.mm',
    'OOExplosionCloudEntity.mm',
    'OOFlashEffectEntity.mm',
    'OOFlasherEntity.mm',
    'OOLaserShotEntity.mm',
    'OOLightParticleEntity.mm',
    'OOParticleSystem.mm',
    'OOPlanetEntity.mm',
    'OOPlasmaBurstEntity.mm',
    'OOPlasmaShotEntity.mm',
    'OOQuiriumCascadeEntity.mm',
    'OORingEffectEntity.mm',
    'OOSparkEntity.mm',
    'OOSunEntity.mm',
    'OOVisualEffectEntity.mm',
    'OOWaypointEntity.mm',
    'PlanetEntity.mm',
    'PlayerEntity.mm',
    'PlayerEntity+FoundationBridge.mm',
    'PlayerEntityContracts.mm',
    'PlayerEntityContracts+FoundationBridge.mm',
    'PlayerEntityControls.mm',
    'PlayerEntityKeyMapper.mm',
    'PlayerEntityLegacyScriptEngine.mm',
    'PlayerEntityLegacyScriptEngine+FoundationBridge.mm',
    'PlayerEntityLoadSave.mm',
    'PlayerEntityScriptMethods.mm',
    'PlayerEntityScriptMethods+FoundationBridge.mm',
    'PlayerEntitySound.mm',
    'PlayerEntitySound+FoundationBridge.mm',
    'PlayerEntityStickMapper.mm',
    'PlayerEntityStickProfile.mm',
    'ProxyPlayerEntity.mm',
    'ShipEntity.mm',
    'ShipEntity+FoundationBridge.mm',
    'ShipEntityAI.mm',
    'ShipEntityLoadRestore.mm',
    'ShipEntityScriptMethods.mm',
    'SkyEntity.mm',
    'StationEntity.mm',
    'StationEntity+FoundationBridge.mm',
    'WormholeEntity.mm',
)

oolite_includes += include_directories('.')

