#!/usr/bin/env python3
"""Generate callObjC()'s name table for entities (bead oo-9ht.44, ADR-0056 amendment oo-9ht.44).

callObjC() on an entity dispatches through kOOJSCallEntityMethods
(upstream/oolite/src/Core/Scripting/OOJSCallEntityMethods.h) instead of reading the Objective-C
method signatures of the entity's object. The table is exactly the instance methods the root
facade's @implementation blocks define (Entity and its categories: the forwarders, the by-name
categories, the shader, beacon and JS categories, the cascade's) that the old signature matcher
could call safely: no argument, or one `const std::string &` argument with a void or oo::PList
result (the two string templates). Lifetime and root-protocol names (init, dealloc, ...) are
left out, as are argument-taking scalar methods (the matcher called them with their argument
missing). Each row keeps the method's #if conditions and, for a typed result, @encode() of the
declared return type, which callObjC() reads through OOShaderUniformTypeFromEncoding() as the
matcher read the method's return type.

    python3 tools/gen-callobjc-entity-table.py           # rewrite the header
    python3 tools/gen-callobjc-entity-table.py --check   # exit 1 if the header is stale
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "upstream/oolite/src"
SOURCES = [
    SRC / "Core/Entities/Entity+ObjCBridge.mm",
    SRC / "Core/Entities/OOQuiriumCascadeEntity+ObjCBridge.mm",
]
OUT = SRC / "Core/Scripting/OOJSCallEntityMethods.h"

# Lifetime and root-protocol names: never callable by name (amendment oo-9ht.74 item 4).
EXCLUDED = {
    "init", "dealloc", "finalize", "retain", "release", "autorelease", "retainCount", "copy",
    "mutableCopy", "self", "class", "superclass", "hash", "description", "debugDescription",
    "isProxy", "zone",
}
STRING_ARG = "const std::string &"


def balanced(text, start):
    """Index just past the parenthesised group that opens at text[start] == '('."""
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                return i + 1
    raise ValueError("unbalanced: " + text)


def norm(t):
    return re.sub(r"\s*&\s*", " &", re.sub(r"\s+", " ", t.strip())).strip()


def parse_method(line):
    """(return type, name, argument type or None) of a '- (T) name[:(A)arg]' definition line, or
    None for a method with more than one argument."""
    rest = line[1:].lstrip()
    end = balanced(rest, 0)
    ret = norm(rest[1:end - 1])
    rest = rest[end:].split("{", 1)[0].split("//", 1)[0].strip()
    m = re.match(r"([A-Za-z_][A-Za-z0-9_]*)(.*)$", rest, re.S)
    name, tail = m.group(1), m.group(2).strip()
    if not tail:
        return ret, name, None
    if not tail.startswith(":"):
        raise ValueError("cannot parse: " + line)
    tail = tail[1:].strip()
    end = balanced(tail, 0)
    arg = norm(tail[1:end - 1])
    after = tail[end:].strip()
    after = re.sub(r"^[A-Za-z_][A-Za-z0-9_]*", "", after).strip()
    if after:
        return None	# another argument
    return ret, name + ":", arg


def rows():
    result = []
    for path in SOURCES:
        conds = []
        inimpl = False
        for line in path.read_text(encoding="utf-8").splitlines():
            s = line.strip()
            if re.match(r"#\s*(if|ifdef|ifndef)\b", s):
                conds.append(s)
                continue
            if re.match(r"#\s*(else|elif)\b", s):
                raise SystemExit(f"{path.name}: #else/#elif is not handled: {s}")
            if re.match(r"#\s*endif\b", s):
                conds.pop()
                continue
            if re.match(r"@implementation\s+Entity\b", line):
                inimpl = True
                continue
            if line.startswith("@end"):
                inimpl = False
                continue
            if not inimpl or not re.match(r"-\s*\(", line):
                continue
            parsed = parse_method(line)
            if parsed is None:
                continue
            ret, name, arg = parsed
            if name.rstrip(":") in EXCLUDED:
                continue
            if arg is None:
                form = {"void": "VoidVoid", "oo::PList": "PListVoid"}.get(ret, "Typed")
            elif arg == STRING_ARG and ret in ("void", "oo::PList"):
                form = "VoidString" if ret == "void" else "PListString"
            else:
                continue	# an argument the templates do not take: not callable by name
            result.append((list(conds), name, form, ret))
    return result


def render():
    out = []
    out.append("/*")
    out.append("")
    out.append("OOJSCallEntityMethods.h")
    out.append("")
    out.append("GENERATED by tools/gen-callobjc-entity-table.py from the root entity facade's @implementation")
    out.append("blocks (Entity+ObjCBridge.mm, OOQuiriumCascadeEntity+ObjCBridge.mm). Do not edit: rerun the")
    out.append("script. callObjC()'s names for an entity (bead oo-9ht.44, ADR-0056 amendment oo-9ht.44): each")
    out.append("is a selector the facade defines with no argument, or with one const std::string & argument")
    out.append("and a void or oo::PList result; a Typed row keeps @encode() of the declared return type.")
    out.append("Included by OOJSCall.mm and its test only.")
    out.append("")
    out.append("*/")
    out.append("")
    out.append("#ifndef OOJSCALLENTITYMETHODS_H")
    out.append("#define OOJSCALLENTITYMETHODS_H")
    out.append("")
    out.append("#import \"Entity.h\"")
    out.append("#import \"ShipEntity.h\"")
    out.append("#import \"PlayerEntity.h\"")
    out.append("#import \"StationEntity.h\"")
    out.append("#import \"OOVisualEffectEntity.h\"")
    out.append("#import \"OOPlanetEntity.h\"")
    out.append("#import \"OOQuiriumCascadeEntity+ObjCBridge.h\"")
    out.append("#include \"oofnd/PList.hpp\"")
    out.append("#include <string>")
    out.append("")
    out.append("enum class OOJSCallEntityMethodForm")
    out.append("{")
    out.append("\tVoidVoid,\t\t// - (void) name")
    out.append("\tVoidString,\t\t// - (void) name:(const std::string &)")
    out.append("\tPListString,\t// - (oo::PList) name:(const std::string &)")
    out.append("\tPListVoid,\t\t// - (oo::PList) name")
    out.append("\tTyped\t\t\t// - (T) name: encoding is @encode(T)")
    out.append("};")
    out.append("")
    out.append("struct OOJSCallEntityMethodRow")
    out.append("{")
    out.append("\tconst char\t\t\t\t\t*name;")
    out.append("\tOOJSCallEntityMethodForm\tform;")
    out.append("\tconst char\t\t\t\t\t*encoding;\t// a Typed row's @encode() of the return type, else null")
    out.append("};")
    out.append("")
    out.append("inline const OOJSCallEntityMethodRow kOOJSCallEntityMethods[] =")
    out.append("{")
    current = []
    for conds, name, form, ret in rows():
        if conds != current:
            for _ in current:
                out.append("#endif")
            for c in conds:
                out.append(c)
            current = conds
        enc = f"@encode({ret})" if form == "Typed" else "nullptr"
        out.append(f"\t{{ \"{name}\",\tOOJSCallEntityMethodForm::{form},\t{enc} }},")
    for _ in current:
        out.append("#endif")
    out.append("};")
    out.append("")
    out.append("#endif\t// OOJSCALLENTITYMETHODS_H")
    out.append("")
    return "\n".join(out)


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run python3 tools/gen-callobjc-entity-table.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({text.count(chr(10) + chr(9) + '{ ')} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
